apiVersion: v1
kind: Service
metadata:
  name:  influxdb-service
  labels:
    app: influxdb
spec:
  selector:
    app:  influxdb
  type:  NodePort
  ports:
  - name: influxdb
    nodePort:  30051
    port:  8086
    targetPort:  8086
