apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-configmap
  labels:
    app: prometheus
data:
  prometheus.yml: |
    global:
      scrape_interval: 10s
      evaluation_interval: 10s
    scrape_configs:
      - job_name: 'prometheus_local'
        static_configs:
          - targets: ['localhost:9090']
      - hob_name: 'fedora_local'
        static_configs:
          - targets: ['192.168.1.11:9100']
